sonar.projectKey=dhanapal-portfolio
sonar.projectName=Dhanapal Portfolio
sonar.projectVersion=1.0

sonar.sources=src,server
sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
